version: '3.8'

services:
  uvdesk:
    image: uvdesk-app:latest
    ports:
      - "8081:80"
    volumes:
      - ./uvdesk:/var/www/uvdesk
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: uvdesk_db
    ports:
      - "3306:3306"
